# Generated by Django 2.0 on 2017-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='image',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
