# Generated by Django 2.0 on 2017-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171219_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
