# Generated by Django 2.0 on 2017-12-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171219_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='images/photos/'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='image',
            field=models.FileField(upload_to='images/categories/'),
        ),
    ]
