# Generated by Django 2.0 on 2017-12-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171219_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='media/images/photos/'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='image',
            field=models.FileField(upload_to='media/images/categories/'),
        ),
    ]
