# Generated by Django 2.0 on 2017-12-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171219_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
